import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/dbConnect';
import Member from '@/lib/models/Member';

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    await dbConnect();

    const body = await request.json();
    
    console.log('Received registration data:', body); // Debug log
    

    console.log('API received:', {
      ...body,
      password: body.password ? '[HIDDEN]' : 'NO PASSWORD'
    });

    // Check if user already exists
    const existingMember = await Member.findOne({
      $or: [
        { email: body.email },
        { phone: body.phone }
      ]
    });

    if (existingMember) {
      return NextResponse.json(
        { success: false, message: 'Email or phone already registered' },
        { status: 400 }
      );
    }

    // Remove fields that should be auto-generated
    const { userId, roleId, registrationId, ...cleanData } = body;
    
    // Create new member with clean data
    const memberData = {
      ...cleanData,
      status: 'inactive', // Set status to inactive by default
      role: body.role || 'member', // Use role from form or default to 'member'
      // userId, roleId, registrationId will be auto-generated by model
    };

    console.log('Creating member with data:', memberData); // Debug log

    const member = new Member(memberData);
    await member.save();

    console.log('Member created:', {
      id: member._id,
      userId: member.userId,
      role: member.role,
      roleId: member.roleId,
      registrationId: member.registrationId,
      status: member.status
    }); // Debug log

    // Remove password from response
    const memberResponse = member.toObject();
    delete memberResponse.password;

    return NextResponse.json({
      success: true,
      message: 'Registration successful. Status: Inactive. Admin will activate your account.',
      registrationId: member.registrationId,
      userId: member.userId,
      data: {
        id: member._id,
        name: member.name,
        email: member.email,
        registrationId: member.registrationId,
        userId: member.userId,
        role: member.role,
        roleId: member.roleId,
        status: member.status,
      }
    }, { status: 201 });

  } catch (error: any) {
    console.error('Registration error:', error);
    
    let message = 'Registration failed';
    if (error.code === 11000) {
      message = 'Duplicate field value entered';
    } else if (error.name === 'ValidationError') {
      message = Object.values(error.errors).map((err: any) => err.message).join(', ');
    }

    return NextResponse.json(
      { success: false, message: `${message} - ${error.message}` },
      { status: 400 }
    );
  }
}

// import { NextRequest, NextResponse } from 'next/server';
// import dbConnect from '@/lib/dbConnect';
// import Member from '@/lib/models/Member';

// export async function POST(request: NextRequest) {
//   try {
//     await dbConnect();

//     const body = await request.json();
    
//     // Check if user already exists
//     const existingMember = await Member.findOne({
//       $or: [
//         { email: body.email },
//         { phone: body.phone }
//       ]
//     });

//     if (existingMember) {
//       return NextResponse.json(
//         { success: false, message: 'Email or phone already registered' },
//         { status: 400 }
//       );
//     }

//     // Create new member with default values
//     const memberData = {
//       ...body,
//       status: 'inactive', // Set status to inactive by default
//       role: 'member', // Default role is member
//     };

//     const member = new Member(memberData);
//     await member.save();

//     // Remove password from response
//     const memberResponse = member.toObject();
//     delete memberResponse.password;

//     return NextResponse.json({
//       success: true,
//       message: 'Registration successful. Status: Inactive. Admin will activate your account.',
//       registrationId: member.registrationId,
//       userId: member.userId,
//       data: {
//         id: member._id,
//         name: member.name,
//         email: member.email,
//         registrationId: member.registrationId,
//         userId: member.userId,
//         role: member.role,
//         status: member.status,
//       }
//     }, { status: 201 });

//   } catch (error: any) {
//     console.error('Registration error:', error);
    
//     let message = 'Registration failed';
//     if (error.code === 11000) {
//       message = 'Duplicate field value entered';
//     } else if (error.name === 'ValidationError') {
//       message = Object.values(error.errors).map((err: any) => err.message).join(', ');
//     }

//     return NextResponse.json(
//       { success: false, message },
//       { status: 400 }
//     );
//   }
// }

// import { NextRequest, NextResponse } from 'next/server';
// import dbConnect from '@/lib/dbConnect';
// import Member from '@/lib/models/Member';

// export async function POST(request: NextRequest) {
//   try {
//     await dbConnect();

//     const body = await request.json();
    
//     // Check if user already exists
//     const existingMember = await Member.findOne({
//       $or: [
//         { email: body.email },
//         { phone: body.phone }
//       ]
//     });

//     if (existingMember) {
//       return NextResponse.json(
//         { success: false, message: 'Email or phone already registered' },
//         { status: 400 }
//       );
//     }

//     // Create new member
//     const member = new Member(body);
//     await member.save();

//     return NextResponse.json({
//       success: true,
//       message: 'Registration successful',
//       registrationId: member.registrationId,
//       data: {
//         id: member._id,
//         name: member.name,
//         email: member.email,
//         registrationId: member.registrationId,
//       }
//     }, { status: 201 });

//   } catch (error: any) {
//     console.error('Registration error:', error);
    
//     let message = 'Registration failed';
//     if (error.code === 11000) {
//       message = 'Duplicate field value entered';
//     } else if (error.name === 'ValidationError') {
//       message = Object.values(error.errors).map((err: any) => err.message).join(', ');
//     }

//     return NextResponse.json(
//       { success: false, message },
//       { status: 400 }
//     );
//   }
// }